EmpleadosEBS/Models/ShoppingCart.cs
using EmpleadosEBS.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmpleadosEBS.Models
{
    public class ShoppingCart
    {
        private readonly ApplicationDbContext _context;

        public ShoppingCart(ApplicationDbContext context)
        {
            _context = context;
        }

        public string ShoppingCartId { get; set; }
        public List<ShoppingCartItem> ShoppingCartItems { get; set; }

        public static ShoppingCart GetCart(IServiceProvider services)
        {
            ISession session = services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;

            var context = services.GetService<ApplicationDbContext>();

            string cartId = session.GetString("CartId") ?? Guid.NewGuid().ToString();

            session.SetString("CartId", cartId);

            return new ShoppingCart(context) { ShoppingCartId = cartId };
        }

        public void AddToCartPlato(Plato plato, int cantidad)
        {
            var shoppingCartItem =
                _context.ShoppingCartItems.SingleOrDefault(
                    s => s.Plato.ID == plato.ID && s.ShoppingCartId == ShoppingCartId);

            if (shoppingCartItem == null)
            {
                shoppingCartItem = new ShoppingCartItem
                {
                    ShoppingCartId = ShoppingCartId,
                    Plato = plato,
                    Cantidad = 1
                };

                _context.ShoppingCartItems.Add(shoppingCartItem);
            }
            else
            {
                shoppingCartItem.Cantidad++;
            }

            _context.SaveChanges();
        }

        public int RemoveFromCartPlato(Plato plato)
        {
            var shoppingCartItem =
                    _context.ShoppingCartItems.SingleOrDefault(
                        s => s.Plato.ID == plato.ID && s.ShoppingCartId == ShoppingCartId);

            var localAmount = 0;

            if (shoppingCartItem != null)
            {
                if (shoppingCartItem.Cantidad > 1)
                {
                    shoppingCartItem.Cantidad--;
                    localAmount = shoppingCartItem.Cantidad;
                }
                else
                {
                    _context.ShoppingCartItems.Remove(shoppingCartItem);
                }
            }

            _context.SaveChanges();

            return localAmount;
        }

        public void AddToCart(Articulo articulo, int cantidad)
        {
            var shoppingCartItem =
                _context.ShoppingCartItems.SingleOrDefault(
                    s => s.Articulo.ID == articulo.ID && s.ShoppingCartId == ShoppingCartId);

            if(shoppingCartItem == null)
            {
                shoppingCartItem = new ShoppingCartItem
                {
                    ShoppingCartId = ShoppingCartId,
                    Articulo = articulo,
                    Cantidad = 1
                };

                _context.ShoppingCartItems.Add(shoppingCartItem);
            }
            else
            {
                shoppingCartItem.Cantidad++;
            }

            _context.SaveChanges();
        }

        public int RemoveFromCart(Articulo articulo)
        {
            var shoppingCartItem =
                    _context.ShoppingCartItems.SingleOrDefault(
                        s => s.Articulo.ID == articulo.ID && s.ShoppingCartId == ShoppingCartId);

            var localAmount = 0;

            if (shoppingCartItem != null)
            {
                if (shoppingCartItem.Cantidad > 1)
                {
                    shoppingCartItem.Cantidad--;
                    localAmount = shoppingCartItem.Cantidad;
                }
                else
                {
                    _context.ShoppingCartItems.Remove(shoppingCartItem);
                }
            }

            _context.SaveChanges();

            return localAmount;
        }

        public List<ShoppingCartItem> GetShoppingCartItems()
        {
            return ShoppingCartItems ??
                (ShoppingCartItems =
                _context.ShoppingCartItems.Where(c => c.ShoppingCartId == ShoppingCartId)
                    .Include(s => s.Articulo).Include(s => s.Plato).ToList());
        }

        public void ClearCart()
        {
            var cartItems = _context
                .ShoppingCartItems
                .Where(cart => cart.ShoppingCartId == ShoppingCartId);

            _context.ShoppingCartItems.RemoveRange(cartItems);

            _context.SaveChanges();
        }

        public double GetShoppingCartTotal()
        {
            var total1 = _context.ShoppingCartItems.Where(c => c.ShoppingCartId == ShoppingCartId)
                .Select(c => c.Articulo.PrecioVenta * c.Cantidad).Sum();

            var total2 = _context.ShoppingCartItems.Where(c => c.ShoppingCartId == ShoppingCartId)
                .Select(c => c.Plato.PrecioVenta * c.Cantidad).Sum();

            var total3 = total1 + total2;

            return total3;
        }
    }
}

EmpleadosEBS/ViewModels/ShoppingCartViewModel.cs
using EmpleadosEBS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmpleadosEBS.ViewModels
{
    public class ShoppingCartViewModel
    {
        public ShoppingCart ShoppingCart { get; set; }
        public double ShoppingCartTotal { get; set; }
    }
}

EmpleadosEBS/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmpleadosEBS.Models;
using EmpleadosEBS.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using EmpleadosEBS.Data;

namespace EmpleadosEBS.Controllers
{
    public class OrderController : Controller
    {

        private readonly IOrderRepository _orderRepository;
        private readonly ShoppingCart _shoppingCart;
        private readonly UserManager<User> _userManager;
        private readonly ApplicationDbContext _context;

        public OrderController(IOrderRepository orderRepository, ShoppingCart shoppingCart, UserManager<User> userManager, ApplicationDbContext context )
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
            _userManager = userManager;
            _context = context;
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Pedido pedido)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            pedido.UserId = userId;

            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            if(pedido.PorDelivery)
            {
                pedido.PrecioVenta = _shoppingCart.GetShoppingCartTotal();
            } else
            {
                pedido.PrecioVenta = _shoppingCart.GetShoppingCartTotal() * 0.90;
            }
            pedido.FechaHora = DateTime.Now;
            pedido.EstadoPedidoID = 1;
            //agrege numero de pedido que parsea la fecha cuando se hace el pedido
            DateTime numeropedido = DateTime.Now;
            pedido.NumeroPedido = Int32.Parse(numeropedido.ToString("yyyyMMdd"));

            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Tu carrito de compras esta vacio por favor agrega algo");
            }

            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(pedido);
                _shoppingCart.ClearCart();
 
                return RedirectToAction("CheckoutComplete");
            }

            return View(pedido);
        }

        public IActionResult CheckoutComplete()
        {
            Random rnd = new Random();
            int espera = rnd.Next(15, 45);

            ViewBag.CheckoutCompleteMessage = "Gracias por su orden";
            ViewBag.TiempoEspera = espera + " minutos";
            return View();
        }
    }
}

EmpleadosEBS/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmpleadosEBS.Models;
using EmpleadosEBS.Repositories;
using EmpleadosEBS.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace EmpleadosEBS.Controllers
{
    public class ShoppingCartController : Controller
    {

        private readonly IArticuloRepository _articuloRepository;
        private readonly IPlatoRepository _platoRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IArticuloRepository articuloRepository, IPlatoRepository platoRepository, ShoppingCart shoppingCart)
        {
            _articuloRepository = articuloRepository;
            _platoRepository = platoRepository;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var sCVM = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(sCVM);
        }

        public RedirectToActionResult AddToShoppingCart(int id)
        {
            var selectedArticulo = _articuloRepository.Articulo.FirstOrDefault(p => p.ID == id);
            if(selectedArticulo != null)
            {
                _shoppingCart.AddToCart(selectedArticulo, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult AddToShoppingCartPlato(int id)
        {
            var selectedPlato = _platoRepository.Plato.FirstOrDefault(p => p.ID == id);
            if (selectedPlato != null)
            {
                _shoppingCart.AddToCartPlato(selectedPlato, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int id)
        {
            var selectedArticulo = _articuloRepository.Articulo.FirstOrDefault(p => p.ID == id);
            if (selectedArticulo != null)
            {
                _shoppingCart.RemoveFromCart(selectedArticulo);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCartPlato(int id)
        {
            var selectedPlato = _platoRepository.Plato.FirstOrDefault(p => p.ID == id);
            if (selectedPlato != null)
            {
                _shoppingCart.RemoveFromCartPlato(selectedPlato);
            }
            return RedirectToAction("Index");
        }
    }
}

EmpleadosEBS/Views/ShoppingCart/Index.cshtml
@model EmpleadosEBS.ViewModels.ShoppingCartViewModel

<div class="row checkoutForm jumbotron" style="margin-top: 40px;">
    <h2>Carrito de Compras</h2>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Cantidad</th>
                <th>Articulo</th>
                <th class="text-right">Precio</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
            {
                if (line.Plato != null)
                {
                    <tr>
                        <td class="text-center">
                            <a class="btn btn-danger" asp-action="RemoveFromShoppingCartPlato" asp-route-id="@line.Plato.ID"><b>-</b></a>
                            <b>@line.Cantidad</b>
                            <a class="btn btn-danger" asp-action="AddToShoppingCartPlato" asp-route-id="@line.Plato.ID"><b>+</b></a>
                        </td>
      
                        <td class="text-left">@line.Plato.Denominacion</td>
                        <td class="text-right">@line.Plato.PrecioVenta.ToString("c")</td>
                        <td class="text-right">
                            @((line.Cantidad * line.Plato.PrecioVenta).ToString("c"))
                        </td>
                        <td class="text-center"><a class="fa fa-times-circle text-danger remove" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCartPlato" asp-route-ID="@line.Plato.ID"></a></td>
                    </tr>
                }
                else if (line.Articulo != null)
                {
                    <tr>
                        <td class="text-center">
                            <a class="btn btn-danger" asp-action="RemoveFromShoppingCart" asp-route-id="@line.Articulo.ID"><b>-</b></a>
                            <b>@line.Cantidad</b>
                            <a class="btn btn-danger" asp-action="AddToShoppingCart" asp-route-id="@line.Articulo.ID"><b>+</b></a>
                        </td>
                        <td class="text-left">@line.Articulo.Denominacion</td>
                        <td class="text-right">@line.Articulo.PrecioVenta.ToString("c")</td>
                        <td class="text-right">
                            @((line.Cantidad * line.Articulo.PrecioVenta).ToString("c"))
                        </td>
                        <td class="text-center"><a class="fa fa-times-circle text-danger remove" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-ID="@line.Articulo.ID"></a></td>
                    </tr>
                }
            }

        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @Model.ShoppingCartTotal.ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>

    <a class="btn btn-primary" asp-controller="Cliente" asp-action="Index">Agregar Mas</a>
    <a class="btn btn-success ml-auto" asp-controller="Order" asp-action="Checkout">Pagar</a>
        
</div>